from pydantic import BaseModel, Field
from typing import Literal, Optional

class ThoughtfulAIQuery(BaseModel):
    """
    Represents a query and its associated answer in the Thoughtful AI system.

    Attributes:
        question (Literal): The exact question string to be asked.
        answer (Literal): The corresponding answer string to the question.
    """
    
    question: Literal[
        "What does the eligibility verification agent (EVA) do?",
        "What does the claims processing agent (CAM) do?",
        "How does the payment posting agent (PHIL) work?",
        "Tell me about Thoughtful AI's Agents.",
        "What are the benefits of using Thoughtful AI's agents?"
    ]
    
    answer: Literal[
        "EVA automates the process of verifying a patient’s eligibility and benefits information in real-time, eliminating manual data entry errors and reducing claim rejections.",
        "CAM streamlines the submission and management of claims, improving accuracy, reducing manual intervention, and accelerating reimbursements.",
        "PHIL automates the posting of payments to patient accounts, ensuring fast, accurate reconciliation of payments and reducing administrative burden.",
        "Thoughtful AI provides a suite of AI-powered automation agents designed to streamline healthcare processes. These include Eligibility Verification (EVA), Claims Processing (CAM), and Payment Posting (PHIL), among others.",
        "Using Thoughtful AI's Agents can significantly reduce administrative costs, improve operational efficiency, and reduce errors in critical processes like claims management and payment posting."
    ]

class SolutionResponse(BaseModel):
    """
    Represents a structured response containing the most relevant query and a conversational agent response.

    Attributes:
        most_relevant_query (Optional[ThoughtfulAIQuery]): The query-answer pair most relevant to the input question.
        conversational_agent_response (str): A natural language response generated by the conversational AI agent.
    """

    most_relevant_query: Optional[ThoughtfulAIQuery]
    conversational_agent_response: str = Field(
        ..., 
        description="Answer the question like a conversational AI agent."
    )
